#numpy
numpy is numerical python
advantage of numerical python
1. Allow several mathmatcials operation
2. faster operation

In [ ]:
import numpy  as np
from time import process_time

list vs numpy time taken

In [ ]:
#time take by list
Python_list =  [i for i in range(10000)]

start_time = process_time()

Python_list = [i+5 for i in Python_list]

end_time = process_time()

print(end_time - start_time)

0.0016377599999994885


In [ ]:
#time taken by numerical python
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00024999299999883817


#numpy Arrays


In [ ]:
# list
my_list = [1,2,3,4,5]
print(type(my_list))
print(my_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [ ]:
np_array = np.array([1,2,3,4,5])
print(type(np_array))

print(np_array)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
#dimension in np_arrays
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
print(a.shape)

(5,)


In [ ]:
b = np.array([(1,2,3,4,5),(6,7,8,9,20)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]


In [ ]:
b.shape

(2, 5)

In [ ]:
b = np.array([(1,2,3,4,5),(6,7,8,9,20)],dtype = float)
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 20.]]


In [ ]:
#initial place_holders in arrays
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create matrix of ones
c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#create matrix of any given number
v = np.full((3,4),5)
print(v)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create identity matrix
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create random value numpy array matrix
b = np.random.random((3,4))
print(b)

[[0.67219332 0.35071045 0.2884732  0.7623987 ]
 [0.95035255 0.6752272  0.69524036 0.97762082]
 [0.51913286 0.9108193  0.16018853 0.46858463]]


In [ ]:
#random integer value array within specific radiant
k = np.random.randint(1,100,(3,4))
print(k)

[[62  2 87 73]
 [51 77 52 38]
 [63 65 40 41]]


In [ ]:
#number of evenly spaced values ----> spacifying the number of values required
x = np.linspace(10,30,6)
print(x)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values ---> specifying the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert alist to np_arrays
list_2 = [1,2,3,4,5]
np_array = np.asarray(list_2)
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#Analysing numpy arrays


In [ ]:
a = np.random.randint(20,90,(5,5))
print(a)

[[23 79 76 57 89]
 [72 31 25 53 55]
 [47 51 86 71 49]
 [51 31 89 54 25]
 [33 48 55 37 28]]


In [ ]:
#shape of the array
a.shape

(5, 5)

In [ ]:
#dimension of the array
a.ndim

2

In [ ]:
#know the number of element in the array
a.size

25

In [ ]:
a.dtype

dtype('int64')

#mathematicals operation on the np array

In [ ]:
#we concat or join the list for exaample
my_list1 = [1,2,3,4,5]
my_list2 = [6,7,8,9,10]
my_list = my_list1 + my_list2
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
b = np.random.randint(20,60,(3,3))
c = np.random.randint(60,90,(3,3))
print(b)
print(c)

[[58 48 23]
 [49 37 54]
 [55 33 30]]
[[82 84 82]
 [60 68 67]
 [74 80 82]]


In [ ]:
print(b+c)
print(b-c)
print(b*c)
print(b/c)

[[140 132 105]
 [109 105 121]
 [129 113 112]]
[[-24 -36 -59]
 [-11 -31 -13]
 [-19 -47 -52]]
[[4756 4032 1886]
 [2940 2516 3618]
 [4070 2640 2460]]
[[0.70731707 0.57142857 0.2804878 ]
 [0.81666667 0.54411765 0.80597015]
 [0.74324324 0.4125     0.36585366]]


In [ ]:
#or we can do this
print(np.add(b,c))
print(np.subtract(b,c))
print(np.multiply(b,c))
print(np.divide(b,c))

[[140 132 105]
 [109 105 121]
 [129 113 112]]
[[-24 -36 -59]
 [-11 -31 -13]
 [-19 -47 -52]]
[[4756 4032 1886]
 [2940 2516 3618]
 [4070 2640 2460]]
[[0.70731707 0.57142857 0.2804878 ]
 [0.81666667 0.54411765 0.80597015]
 [0.74324324 0.4125     0.36585366]]


Arrays Manipulation

In [ ]:
array = np.random.randint(20,60,(3,3))
print(array)

[[21 51 35]
 [44 58 51]
 [26 51 25]]


In [ ]:
#transspose
transspose_array = array.T
print(transspose_array)

[[21 44 26]
 [51 58 51]
 [35 51 25]]


In [ ]:
#another method
transpose = np.transpose(array)
print(transpose)

[[21 44 26]
 [51 58 51]
 [35 51 25]]


In [ ]:
#reshape the array
a = np.random.randint(20,60,(2,3))
print(a)
a.shape

[[55 59 35]
 [30 22 20]]


(2, 3)

In [ ]:
b = a.reshape(3,2)
print(b)
b.shape

[[55 59]
 [35 30]
 [22 20]]


(3, 2)