In [2]:
import numpy as np

Creating a matrix using Numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[2,3,5],[6,7,4], [4,9,6]])
print(matrix_2)

[[2 3 5]
 [6 7 4]
 [4 9 6]]


In [6]:
matrix_2.shape

(3, 3)

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.98897822 0.51528971 0.18532234]
 [0.38542932 0.22158382 0.50364583]
 [0.45576394 0.69821051 0.61937334]]


In [8]:
#creating matrix with random integers
random_matrix = np.random.rand(100,4,5)
print(random_matrix)

[[[0.49830191 0.32222754 0.07243708 0.08389891 0.15627354]
  [0.39792887 0.71160273 0.46295645 0.13663277 0.23311778]
  [0.40009461 0.85665171 0.38251228 0.29077435 0.2306262 ]
  [0.31357418 0.47652501 0.23009739 0.34787262 0.26256005]]

 [[0.05392215 0.09605385 0.97840079 0.81865369 0.61977362]
  [0.03814013 0.69353514 0.22441472 0.81658073 0.79654703]
  [0.63454051 0.12228193 0.05625947 0.39238662 0.53711462]
  [0.86789672 0.76264949 0.57526794 0.66880359 0.14689428]]

 [[0.73803721 0.44855902 0.14080734 0.47811125 0.90316517]
  [0.17486574 0.13094141 0.00581689 0.11739824 0.57777436]
  [0.3629192  0.14746987 0.61919973 0.49963531 0.83926371]
  [0.73951495 0.64155037 0.8040923  0.04370693 0.06542194]]

 ...

 [[0.70671561 0.90654756 0.84589225 0.92913599 0.48005225]
  [0.92861699 0.22219713 0.75738638 0.95440023 0.33916911]
  [0.36240082 0.0802032  0.83354103 0.30164764 0.14118494]
  [0.681734   0.15633532 0.57369934 0.42434134 0.58375852]]

 [[0.75300195 0.33860927 0.33743118 0.4138

matrix qith all the value 1

In [9]:
matrix_3 = np.ones((3,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


NUll matrix or zero matrix

In [10]:
null_matrix = np.zeros((3,3), dtype= int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


identity matrix

In [11]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of matrix

In [12]:
a = np.random.randint(100 , size= (3,3))
print(a)

[[31 15 65]
 [67 15 27]
 [40 32  5]]


In [13]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[31 67 40]
 [15 15 32]
 [65 27  5]]


**Addition of Matrix** -
two matrices can be added only if have same shape that means both matrices should have same numbers row column

In [14]:
#creating matrices
A= np.array([[2,3],[6,7]])
B= np.array([[2,3],[6,7]])

In [15]:
print(A)
print(B)

[[2 3]
 [6 7]]
[[2 3]
 [6 7]]


In [16]:
#addition of matrix
c= A+B
print(c)

[[ 4  6]
 [12 14]]


In [17]:
#creating two matrices with random value
matrix_1 = np.random.randint(10 , size= (3,3))
matrix_2 = np.random.randint(20 , size= (3,3))

In [18]:
print(matrix_1)


[[5 8 7]
 [1 4 8]
 [5 7 3]]


In [19]:
print(matrix_2)

[[18  7  1]
 [14 14  7]
 [ 3 11 15]]


In [20]:
sum = np.add(matrix_1 , matrix_2)
print(sum)

[[23 15  8]
 [15 18 15]
 [ 8 18 18]]


In [21]:
#creating two matrices with random value
matrix_1 = np.random.randint(10 , size= (3,3))
matrix_2 = np.random.randint(20 , size= (3,4))

In [22]:
print(matrix_1)
print(matrix_2)

[[1 4 5]
 [1 2 2]
 [8 3 6]]
[[16  9 10  1]
 [13 11  7 12]
 [ 4  0 19  4]]


In [23]:
sum = np.add(matrix_1 , matrix_2)
print(sum)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because of diffrent shape of the matrix

Subtraction of the matrices

In [24]:
#creating matrices for diffrence operation
A = np.array([[2,3],[6,7]])
B = np.array([[2,3],[6,7]])
print(A)
print(B)

[[2 3]
 [6 7]]
[[2 3]
 [6 7]]


In [25]:
diffrence= A-B
print(diffrence)

[[0 0]
 [0 0]]


In [26]:
diff =np.subtract(A,B)
print(diff)

[[0 0]
 [0 0]]


In [27]:
A = np.array([[2,3],[6,8]])
B = 2*A
print(B)

[[ 4  6]
 [12 16]]


In [28]:
A = 5
Y = np.array([[2,3],[6,8]])
print(Y)

[[2 3]
 [6 8]]


In [30]:
product = np.multiply(A,Y)
print(product)

[[10 15]
 [30 40]]


multiplying two Matrices

In [49]:
matrix_6 = np.random.randint(5, size= (3,4))
matrix_4 = np.random.randint(10, size= (3,4))

In [50]:
print(matrix_6)

[[4 2 0 1]
 [1 1 4 0]
 [0 0 2 0]]


In [34]:
print(matrix_4)

[[8 5 0]
 [5 5 5]
 [8 7 8]]


In [41]:
product = np.dot(matrix_3 , matrix_4)
print(product)

[[16  5 18 17]
 [16  5 18 17]
 [16  5 18 17]]
